### ISSUE TITLE
mqtt client and files

### ISSUE THREAD

**Issue by martcs** [roberttidey/RotaryEncoderButton#2]
Hi, im set mqtt server address, port. Change line:"if (mqttClient.connect("ESP8266mqttClient")) {" my mqtt server not use user and password. Im not see in serial monitor connection to mqtt (only WM connection and encoder value),and encoder topic on mqtt server not see of course. Line "#define MQTT" is uncommented. Maybe is something else for starting mqtt publishing? where can set topic name. I tray upload files (http://ipaddress/upload), but after reset all is gone:
handleFileRead: /
handleFileUpload Name: /edit.htm.gz
handleFileUpload Data: 2048
handleFileUpload Data: 2048
handleFileUpload Data: 20
handleFileUpload Size: 4116
handleFileRead: /
handleFileUpload Name: /favicon.ico
handleFileUpload Data: 1150
handleFileUpload Size: 1150
handleFileUpload Name: /graphs.js.gz
handleFileUpload Data: 1971
handleFileUpload Size: 1971
handleFileUpload Name: /index.htm
handleFileUpload Data: 620
handleFileUpload Size: 620
handleFileUpload Name: /linkInit.txt
handleFileUpload Data: 1
handleFileUpload Size: 1
handleFileUpload Name: /rotaryEncoderConfig.txt
handleFileUpload Data: 603
handleFileUpload Size: 603
handleFileRead: /
handleFileRead: /
handleFileRead: /
handleFileRead: /edit.htm
handleFileRead: /index
handleFileRead: /data
handleFileRead: /data/upload

And that is from serial monitor on start:

Set up Wifi services
Set up managed Web
*WM: [1] AutoConnect 
*WM: [2] Connecting as wifi client... 
*WM: [3] STA static IP:
*WM: [2] setSTAConfig static ip not set, skipping 
*WM: [1] Connecting to SAVED AP: WIFI22
*WM: [3] Using Password: 
*WM: [3] WiFi_enableSTA enable
*WM: [3] enableSTA PERSISTENT ON 
scandone
*WM: [1] connectTimeout not set, ESP waitForConnectResult... 
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 4

connected with WIFI22, channel 1
dhcp client start...
cnt 
ip:192.168.88.215,mask:255.255.255.0,gw:192.168.88.1
*WM: [2] Connection result: WL_CONNECTED
*WM: [3] lastconxresult: WL_CONNECTED
*WM: [1] AutoConnect: SUCCESS 
*WM: [1] STA IP Address: 192.168.88.215
Set up web server
/rotaryEncoderConfig.txt not found. Use default encoder
sleepMask:0
Set up complete
pm open,type:2 0
Rotary position = 1
Rotary direction = 1
Button pulse = -1

Rotary position = 2
Rotary direction = 1
Button pulse = -1

Rotary position = 3
Rotary direction = 1
Button pulse = -1

Rotary position = 4
Rotary direction = 1
Button pulse = -1

**Comment by roberttidey** [comment]
First thing to sort is why your file upload is problematic. Without that succeeding and it can read the rotaryEncoderConfig.txt then nothing is going to work.

What size filing system (e.g. SPIFFS) have you allocated when you compile the code?

After doing the file upload operations then you should be able to do ip/edit which will show the files present and allow you to perform further file uploads or updates more easily. Is that working?

That should survive a reset and you should be able to ip/edit and still see the files. I did a quick sanity check on this and it works OK.

Once you can do that then you can configure an encoder to perform a mqtt.publish(topic, payload) where topic is the Par1 parameter and payload is the actionString which can have various parameters substituted e.g. encoder position or other parameters from the config line.. I've noticed the actionString wasn't being fully constructed for mqtt operations but that is corrected now.

**Comment by martcs** [comment]
Thanks, it was my fault. I not set FS size, after that (set 1MB) all was ok, except mqtt. I can upload files and save after restart. config file loading. But anyway  i not see connection to mqtt server... 

connected with WIFI22, channel 1
dhcp client start...
cnt 
wifi evt: 0
ip:192.168.88.215,mask:255.255.255.0,gw:192.168.88.1
wifi evt: 3
*WM: [2] Connection result: WL_CONNECTED
*WM: [3] lastconxresult: WL_CONNECTED
*WM: [1] AutoConnect: SUCCESS 
*WM: [1] STA IP Address: 192.168.88.215
[MDNSResponder] STA interface selected
[MDNSResponder] _allocUDPContext
Set up web server
[MDNSResponder] addService: Succeeded to add 'rotaryEncoderY.http.tcp'!
Config loaded from file OK
SPIFFS_close: fd=1
SPIFFS_close: fd=1
Config loaded
host:rotaryEncoderY
noChangeTimeout:30000
SPIFFS_close: fd=2
SPIFFS_close: fd=2
sleepMask:1
Set up complete
pm open,type:2 0
Rotary position = 10
Rotary direction = 1
Button pulse = 0
[hostByName] Host: 192.168.88.215 is a IP!
SPIFFS_close: fd=2
SPIFFS_close: fd=3
SPIFFS_close: fd=3
Rotary position = 8
Rotary direction = -1
Button pulse = 0
[hostByName] Host: 192.168.88.215 is a IP!
SPIFFS_close: fd=2
SPIFFS_close: fd=3
SPIFFS_close: fd=3
Rotary position = 9
Rotary direction = 1
Button pulse = 0
[hostByName] Host: 192.168.88.215 is a IP!
SPIFFS_close: fd=2
SPIFFS_close: fd=3
SPIFFS_close: fd=3
Rotary position = 19
Rotary direction = 1
Button pulse = 0
[hostByName] Host: 192.168.88.215 is a IP!
SPIFFS_close: fd=2
SPIFFS_close: fd=3
SPIFFS_close: fd=3
state: 5 -> 0 (0)
rm 0
pm close 7
del if0
usl
mode : null
wifi evt: 1
STA disconnect: 8
wifi evt: 8
force slp enable,type: 2
fpm open,type:2 0
enter deep sleep

**Comment by roberttidey** [comment]
OK. Good that FS is sorted.

Can you share your rotaryEncoderConfig.txt file so I can see mqtt set up?

**Comment by martcs** [comment]
Hi, im not realy understand configuration, i only change ip
#Config file for rotary Encoder
#lines are host;noChangeTimeout;ADC_CAL;encoder definitions
rotaryEncoderY
30000
0.976
#up to 3 encoder defintions pin1, pin2, button, min, max, start, action, interval, action template, par1, par2, par3, par4, par5.
#Use -1 for pin1 to indicate n/a
5,4,12,0,32,15,2,2000,$t$c!$l|LoungeLight|Bright$p,192.168.88.144,9760,R1D1,par4,par5
-1,-1,-1,0,100,50,0,500,http://192.168.88.144/encoderChange?encoder$e&position=$p&direction=$d,par1,par2,par3,par4,par5
-1,-1,-1,0,100,50,0,500,http://192.168.88.144/encoderChange?encoder$e&position=$p&direction=$d,par1,par2,par3,par4,par5
`

**Comment by roberttidey** [comment]
OK. One needs to set one of the encoder definitions to do what you want.

Some explanation on how to do this is in the instructable https://www.instructables.com/Rotary-Encoder-Button/ in the section configuration but I'll illustrate that here with an example.

Look first at the example in the supplied file 

5,4,12,0,32,15,2,2000,$t$c!$l|LoungeLight|Bright$p,192.168.88.144,9760,R1D1,par4,par5

This has a number of fields separated by ','

Here it is saying there is an encoder which uses GPIO 4 and 5 for the rotation inputs and GPIO12 for the central button

The next 3 numbers define the range of values as the encoder is rotated. Here it says the encoder should produce values from 0 to 32 and should have an initial value when first used of 15.

The next value (action) is very important as it determines how the software is going to respond when the rotation values changes. The software supports 4 different types of action (0=None,1=web GET,2=UDP / Lightwave,4=MQTT)

The example given is for controlling UDP devices like LightwaveRF home automation devices like lighting or switches. 

The next value on the line controls how often a change in value can trigger this action. This allows avoiding triggering multiple actions if the control is rotated fast. So with the value shown (2000) actions can only be triggered at 2 second intervals. So, say it is being used to control a light dimmer and you rapidly rotate the encoder to go from value 10 - 20 then it triggers one action sending the final value 20 rather than attempting to send a stream of each individual value.

The next value is called the actionString and is the primary piece of information associated with the action. It is probably easier to understand this bit by looking at the actionString in the second example encoder (which is not actually set up with real encoder pins)  http://192.168.88.144/encoderChange?encoder$e&position=$p&direction=$d

This would be an actionString which could be used with an action type of 1 (web GET). It defines what web url to construct so it includes the basic web address and then 3 GET parameters called encoder, position and direction. The interesting part is that parts of the actionString with a $ will be substituted before the url is called. So the $e will get substituted by the encoder number, $p with its position value, and $d with the last movement direction (up or down). The full list of possible substitutions is in the instructable. 

The remaining parameters on the line par1 - par5 are used in different ways depending on the action, So for UDP par1 controls which port to access.

Returning now to mqtt you need to set the action type to 4. For mqtt par1 is used for the topic. Finally you set the actionString to control the payload sent to this topic.

So it would look something like

5,4,12,0,32,15,4,2000,$p,topic,par2,par3,par4,par5

where topic might be something like encoders/1/position

**Comment by martcs** [comment]
Thanks, this explaining was very usefull. Now all work. Just mqtt in ino is define as action number 3. Working string in configuration for me is:5,4,12,0,32,15,3,2000,$p,topic,par2,par3,par4,par5
Mqtt give "topic/value" without any other parameters. How to add moving direction and push button on/off toggle in mqtt string?

**Comment by roberttidey** [comment]
I have corrected the instructable to have mqtt as action=3.

The moving direction is referenced by $d and the buttonPush by $b

$d has values of -1,0,1 for down, no change, up
$b has values of 0=Nothing,1=short push,2=long push

So you could make the actionString something like $p:$d:$b which would report all three values to that topic.

**Comment by martcs** [comment]
Thanks again for your patience, all work as volume remote
 : your remote->mqtt->nodered_>domoticz->logitech media server.
but maybe better will be try your remote->http->logitech media server. anyway great project!

**Comment by roberttidey** [comment]
If its a squeezebox then the urls here might do the trick.

http://arduino-projects4u.com/squeezebox/

One does volume so you could just put $p where the volume value goes.
